packages:
  - apps/*
  - packages/*

catalogs:
  prisma:
    prisma: latest

ignoredBuiltDependencies:
  - esbuild
  - prisma

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - bcrypt
  - sharp
  - unrs-resolver
